### ISSUE TITLE
Error during loading sample Producer Consumer jar

### ISSUE THREAD

**Issue by abeneto** [dukeboard/kevoree#133]
Hello,

I compile the Producer Consumer module with maven 3 without any problem. I load it correctly by the editor, but when i put the two components in a node and i try to do the push, i get this error. I get this all time, and in the diferent sample projects:

13:13 INFO: Resolving ............. /packages[org]/packages[kevoree]/packages[sample]/deployUnits[hashcode=,name=org.kevoree.sample.producerconsumer,version=1.0-SNAPSHOT]
13:14 ERROR: No metadata file found for org.kevoree.sample/org.kevoree.sample.producerconsumer/1.0-SNAPSHOT
13:14 INFO: Resolved in 1333ms
13:14 ERROR: Unable to resolve /packages[org]/packages[kevoree]/packages[sample]/deployUnits[hashcode=,name=org.kevoree.sample.producerconsumer,version=1.0-SNAPSHOT]
13:14 WARN: Error during execution of AddDeployUnit org.kevoree.sample/org.kevoree.sample.producerconsumer/1.0-SNAPSHOT/
13:14 WARN: JavaSENode is aborting last update...
13:14 WARN: JavaSENode update aborted in 1353 ms
13:14 INFO: End deploy result=false-1353
13:14 INFO: WSGroup "sync" update result: false

Whats wrong?

Thanks!! :)

**Comment by gnain** [comment]
Hi,

Thanks for the report ! :-)
First of all I need the version of Kevoree you are using.
The last version is 5.2.5, please check that the editor and runtime are in 5.2.5.
Please also check that the libraries used are 5.2.2.
Finally, check the version of Kevoree used in the POM of the sample, upgrade if necessary.
I just checked on the samples repository, it seems that the version is outdated :-)
I'm updating the samples while you perform these checks.

Best,

**Comment by gnain** [comment]
Hi again,
We just released a new version of libraries (5.2.3) and of the samples.
Try to download it again and run again the process.

**Comment by abeneto** [comment]
Hi!

I use the version 5.2.5 of the editor and the runtime. I'm going to try download the sample project again an run the process. When I get the results of execution will I communicate it to you.

A lot of thanks! :)

**Comment by abeneto** [comment]
It works perfectly! And yes, the versions of the libraries are the 5.2.3

A lot of thanks again :)

![image](https://cloud.githubusercontent.com/assets/10678209/6133758/7bbe8b50-b15c-11e4-9e63-553d1176676b.png)

**Comment by gnain** [comment]
You're welcome :-)
Do not hesitate if you have any other issue.
Best regards,
